### ISSUE TITLE
error in runing the below code 

### ISSUE THREAD

**Issue by akbzam** [bterwijn/memory_graph#1]
hi
I installed memory_graph with pip install memory_graph aso I installed graphviz .
but when I want to run the below code, I get an error message. (it is on your git page also in below address:
# from:https://pypi.org/project/memory-graph/  )
from memory_graph import d

my_squares = []
my_squares_ref = my_squares
for i in range(5):
    my_squares.append(i**2)
    d()
my_squares_copy = my_squares.copy()
d()

the error message is:
> %Run debuging.py
debugging, in file:"D:\akb_python\akb_py_projects\memory_graph\debuging.py" line:19 function:"<module>"
my_squares: [0]
my_squares_ref: [0]
i: 0
Error: Could not open "memory_graph.gv.pdf" for writing : Permission denied
Traceback (most recent call last):
  File "C:\Users\akbar\AppData\Roaming\Python\Python310\site-packages\graphviz\backend\execute.py", line 91, in run_check
    proc.check_returncode()
  File "C:\Program Files (x86)\Thonny\lib\subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '[WindowsPath('dot'), '-Kdot', '-Tpdf', '-O', 'memory_graph.gv']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\akb_python\akb_py_projects\memory_graph\debuging.py", line 19, in <module>
    d()
  File "C:\Users\akbar\AppData\Roaming\Python\Python310\site-packages\memory_graph\__init__.py", line 79, in d
    grph.view()
  File "C:\Users\akbar\AppData\Roaming\Python\Python310\site-packages\graphviz\_tools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\akbar\AppData\Roaming\Python\Python310\site-packages\graphviz\rendering.py", line 185, in view
    return self.render(filename=filename, directory=directory, view=True,
  File "C:\Users\akbar\AppData\Roaming\Python\Python310\site-packages\graphviz\_tools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\akbar\AppData\Roaming\Python\Python310\site-packages\graphviz\rendering.py", line 122, in render
    rendered = self._render(*args, **kwargs)
  File "C:\Users\akbar\AppData\Roaming\Python\Python310\site-packages\graphviz\_tools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\akbar\AppData\Roaming\Python\Python310\site-packages\graphviz\backend\rendering.py", line 324, in render
    execute.run_check(cmd,
  File "C:\Users\akbar\AppData\Roaming\Python\Python310\site-packages\graphviz\backend\execute.py", line 93, in run_check
    raise CalledProcessError(*e.args)
graphviz.backend.execute.CalledProcessError: Command '[WindowsPath('dot'), '-Kdot', '-Tpdf', '-O', 'memory_graph.gv']' returned non-zero exit status 1. [stderr: b'Error: Could not open "memory_graph.gv.pdf" for writing : Permission denied\r\n']

if i installed memory_graphbad? what is problem?
thanks

**Comment by bterwijn** [comment]
Hello Akbzam,

I could reproduce your problem on Windows11 with Adobe Acrobat reader as default PDF reader. The problem is that Adobe Acrobat reader doesn't refresh when the PDF it has open gets updated on disk. Instead it blocks the update and causes a "Could not open "*.pdf" for writing : Permission denied" error to be generated. The solution is installing a PDF reader that does refresh, I suggest using "Evince" but there are others, and setting it as the default PDF reader.

Thanks for reporting this problem, I'll add a new troubleshooting item about it.

Best regards,
Bas Terwijn

**Comment by akbzam** [comment]
Thanks for attention and reply

Yahoo Mail: Search, Organize, Conquer 
 
  On Tue, Mar 5, 2024 at 1:59 AM, Bas ***@***.***> wrote:   


Hello Akbzam,

I could reproduce your problem on Windows11 with Adobe Acrobat reader as default PDF reader. The problem is that Adobe Acrobat reader doesn't refresh when the PDF it has open gets updated on disk. Instead it blocks the update and causes a "Could not open "*.pdf" for writing : Permission denied" error to be generated. The solution is installing a PDF reader that does refresh, I suggest using "Evince" but there are others, and setting it as the default PDF reader.

Thanks for reporting this problem, I'll add a new troubleshooting item about it.

Best regards,
Bas Terwijn

**Comment by akbzam** [comment]
hiEvince is for Linux. am I right?What PDF reader that does refresh, do you know?thanks
    On Tuesday, 5 March 2024 at 01:59:11 GMT+3:30, Bas Terwijn ***@***.***> wrote:  
 
 


Hello Akbzam,

I could reproduce your problem on Windows11 with Adobe Acrobat reader as default PDF reader. The problem is that Adobe Acrobat reader doesn't refresh when the PDF it has open gets updated on disk. Instead it blocks the update and causes a "Could not open "*.pdf" for writing : Permission denied" error to be generated. The solution is installing a PDF reader that does refresh, I suggest using "Evince" but there are others, and setting it as the default PDF reader.

Thanks for reporting this problem, I'll add a new troubleshooting item about it.

Best regards,
Bas Terwijn

**Comment by bterwijn** [comment]
Hello Akbzam,

You should be able to intall Evince on windows too:

  https://www.fosshub.com/Evince.html

Kind regards,
Bas
